### ISSUE TITLE
Amalgam: C++20 Updates

### ISSUE THREAD

**Issue by calebwherry** [howsoai/amalgam#13]
Update compiler settings to use C++20 and also any subtasks that can use C++20 features can be linked here.

Also search for any TODOs in code base with "TODO 15993" for items to update.

- [x] #14 

[ADO link](https://diveplane.visualstudio.com/dp/_workitems/edit/15993)

**Comment by dawnhogan** [comment]
- [ ] address subtask issue

**Comment by calebwherry** [comment]
Closing this as Howso issues are still currently tracked internally, not on GitHub.
